name: Deep embedded Music tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tensorflow/tensorflow:2.1.0-gpu-py3
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          apt-get -y install git
          apt-get -y install zip
          apt-get -y install unzip
          apt-get -y install libsndfile1
          apt-get -y install ffmpeg
          apt -y install git
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: python -m pytest test/ -vv
